swagger: '2.0'
info:
  version: 0.0.1
  title: Retobackend
  description: Ejemplo de API (documentación escrita de cero en formato Yaml).
  
host: "localhost:8080"
basePath: /
consumes: 
  - application/json
produces: 
  - application/json
paths:
  /customers:
    get:
      operationId: findAll
      responses:
        200:
          description: Obtiene todos los registros.
          schema:
            type: "array"
            items:
              $ref: "#/definitions/CustomerGet"
    post:
      operationId: addCustomer
      parameters:
        - name: customer
          in: body
          description: registro a guardar
          schema:
            $ref: "#/definitions/CustomerPost"
      responses:
        201:
          description: Customer guardado correctamente.
        500:
          description: Error interno a intentar guardar.
  /customers/statistics:
    get:
      operationId: getStatsCustomer
      responses:
        200:
          description: Obtiene estadisticas de customer.
          schema:
            $ref: "#/definitions/Statistics"
          
definitions:
  CustomerPost:
    type: "object"
    properties:
      nombre:
        type: "string"
        description: "Nombre del cliente/customer"
      apellido:
        type: "string"
        description: "Apellido del cliente"
      fechaNacimiento:
        type: "string"
        description: "Fecha de nacimiento del cliente en formato YYYY-MM-DD"

  CustomerGet:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Identificador"
      nombre:
        type: "string"
        description: "Nombre del cliente/customer"
      apellido:
        type: "string"
        description: "Apellido del cliente"
      edad:
        type: "integer"
        description: "Edad del cliente"
      fechaNacimiento:
        type: "string"
        description: "Fecha de nacimiento del cliente en formato YYYY-MM-DD"
      fechaMuerte:
        type: "string"
        description: "Fecha de muerte probable del cliente en formato YYYY-MM-DD"

  Statistics:
    type: "object"
    properties:
      edadPromedio:
        type: "number"
        description: "Edad promedio de todos los clientes/customers."
      desvEstandar:
        type: "number"
        description: "Desviación estándar de la edad de los clientes."
      